withdrawal-server/src/api/status.rs

withdrawal status: change lowercase to snake case

---

.github/workflows/ci.yaml

For now, let's keep checks optional

feat(ci): Add comprehensive GitHub Actions workflow

---

.github/workflows/ci.yaml

Updated GitHub Actions dependencies to use explicit version specifications.
* Changed rust-toolchain action to use explicit version (v1)
* Made toolchain specification explicit using with syntax
* Updated install-action to use explicit version (v2)
* Made cargo-nextest installation explicit using with syntax
* Improves CI reproducibility through explicit action versioning
* Makes dependency management easier (clearer version tracking and updates)
* Enables automated version checking and update proposals via Dependabot (supporting quick security patch adoption)

Update GitHub Actions workflow dependencies

---

.github/workflows/ci.yaml
.lefthook.yml

Enhanced clippy configuration to treat performance and correctness warnings as errors.
* Added performance warnings (clippy::perf) as errors in CI clippy check
* Added correctness warnings (clippy::correctness) as errors in CI clippy check
* Applied the same configuration to pre-commit hook
* Enables early detection of performance issues
* More strictly checks potential correctness problems in code
* Ensures consistency by applying the same lint rules in CI and development environment

Enhance clippy configuration with performance and correctness checks

---

.config/nextest.toml
.github/workflows/ci.yaml
client-sdk/Cargo.toml
client-sdk/src/external_api/contract/rollup_contract.rs
tests/tests/store_vault_server.rs
validity-prover/tests/post_blocks.rs

* Added nextest configuration file (timeout, fail-fast, etc.)
* Set up CI test environment (postgres, anvil, and env values)
* Improved test code

Improve test infrastructure and reliability

---

validity-prover/migrations/20250209032216_add_idx_prover_tasks_status.down.sql
validity-prover/migrations/20250209032216_add_idx_prover_tasks_status.up.sql
withdrawal-server/migrations/20250209032446_add_idx_withdrawals_hash.down.sql
withdrawal-server/migrations/20250209032446_add_idx_withdrawals_hash.up.sql

Added database indexes to improve query performance.
* validity-prover: Added composite index to `prover_tasks` table
* Index on `assigned` and `completed` columns
* withdrawal-server: Added index to `withdrawals` table
* Index on `withdrawal_hash` column
* Faster prover task lookups
* Improved withdrawal search performance

Add database indexes for performance optimization

---

Cargo.lock
Cargo.toml

Reverts InternetMaximalism/intmax2#149

Revert "chore(deps): bump uuid from 1.12.1 to 1.13.1"

---

cli/src/args.rs
cli/src/cli/error.rs
cli/src/cli/send.rs
cli/src/cli/sync.rs
cli/src/cli/withdrawal.rs
cli/src/main.rs
client-sdk/src/client/client.rs
client-sdk/src/client/sync/sync_balance.rs
wasm/js-test/src/main.ts
wasm/src/lib.rs

Implemented two new functions
- `get_tx_status`: Retrieves the status of a transaction after submission
- `resync`: Re-synchronizes balance proofs

Some additional utils

---

cli/src/cli/send.rs
client-sdk/src/external_api/private_zkp_server.rs
interfaces/src/api/private_zkp_server/types.rs

Improved private-zkp-server-client's error handling, and simplifying request type.

Minor fix on private-zkp-server-client

---

cli/src/cli/client.rs
cli/src/cli/sync.rs
cli/src/env_var.rs
client-sdk/src/client/client.rs
client-sdk/src/client/fee_payment.rs
client-sdk/src/client/fee_proof.rs
client-sdk/src/client/history.rs
client-sdk/src/client/misc/payment_memo.rs
client-sdk/src/client/receive_validation.rs
client-sdk/src/client/strategy/common.rs
client-sdk/src/client/strategy/deposit.rs
client-sdk/src/client/strategy/mining.rs
client-sdk/src/client/strategy/strategy.rs
client-sdk/src/client/strategy/transfer.rs
client-sdk/src/client/strategy/tx.rs
client-sdk/src/client/strategy/tx_status.rs
client-sdk/src/client/strategy/withdrawal.rs
client-sdk/src/client/sync/balance_logic.rs
client-sdk/src/client/sync/sync_balance.rs
client-sdk/src/client/sync/sync_claims.rs
client-sdk/src/client/sync/sync_withdrawals.rs
client-sdk/src/client/sync/utils.rs
client-sdk/src/external_api/store_vault_server.rs
interfaces/src/api/store_vault_server/interface.rs
wasm/js-test/src/setup.ts
wasm/src/client.rs
wasm/src/fee_payment.rs
wasm/src/lib.rs
wasm/src/misc.rs
wasm/src/native.rs

Changed the client's dependency trait to a dynamic dispatcher, allowing for runtime switching between private zkp server and balance prover.

Dynamic dispathcer

---

Cargo.lock
Cargo.toml
validity-prover-worker/.env.example
validity-prover-worker/Cargo.toml
validity-prover-worker/src/app/worker.rs
validity-prover-worker/src/lib.rs
validity-prover-worker/src/main.rs

This PR implements concurrent parallel processing for validity prover workers. The number of parallel processes can now be configured through the NUM_PROCESS environment variable.

Enabled Parallel Processing for Validity Prover Workers

---

Cargo.lock
Cargo.toml
block-builder/.env.example
block-builder/src/app/block_builder.rs
block-builder/src/app/error.rs

If `BENEFICIARY_PUBKEY` is not set, it will now be automatically generated from `BLOCK_BUILDER_PRIVATE_KEY`.

Auto generated beneficiary

---

block-builder/src/api/routes.rs
block-builder/src/app/block_builder.rs
block-builder/src/app/error.rs
block-builder/src/app/jobs.rs

- Enhanced fee info validation by adding checks for:
- Block builder RPC connection status
- Sufficient ETH balance exceeding the allowance
This prevents sending requests for blocks that cannot be executed.
- Implemented automatic job restart mechanism on failure
- Improved heartbeat accuracy by utilizing tokio interval

Feat: Enhance validation and reliability with fee checks and auto-restart for block builder

---

interfaces/src/api/validity_prover/types.rs
validity-prover/src/api/state.rs
validity-prover/src/api/validity_prover.rs
validity-prover/src/app/error.rs
validity-prover/src/app/observer.rs

- Improve inconsistency check for chceckpoint
- Added new validity prover endpoint `get_last_deposit_id`

Improve inconsistency check for checkpoint

---

Cargo.lock
block-builder/.env.example
block-builder/src/app/block_builder.rs
block-builder/src/app/block_post.rs
block-builder/src/app/jobs.rs
block-builder/src/lib.rs
cli/src/cli/claim.rs
cli/src/cli/deposit.rs
client-sdk/src/external_api/contract/block_builder_registry.rs
client-sdk/src/external_api/contract/block_builder_reward.rs
client-sdk/src/external_api/contract/erc1155_contract.rs
client-sdk/src/external_api/contract/erc20_contract.rs
client-sdk/src/external_api/contract/erc721_contract.rs
client-sdk/src/external_api/contract/handlers.rs
client-sdk/src/external_api/contract/liquidity_contract.rs
client-sdk/src/external_api/contract/rollup_contract.rs
client-sdk/src/external_api/contract/withdrawal_contract.rs
tests/Cargo.toml
tests/tests/load_test.rs
tests/tests/post_blocks.rs

- Added new env to block builder: `GAS_LIMIT_FOR_BLOCK_POST=400000`
- Added `load_test`

Specify gas limit

---

client-sdk/src/client/client.rs
wasm/src/js_types/data.rs

From the requirement from the frontend, I added `tx_digest` to `TxResult`.

feat!: added tx_digest to tx result

---

client-sdk/src/client/client.rs

Added buffer time for the expiry of the block proposal.
This is to prevent "expiry too far" error when the client time is not synced with the server time.

fix: add expiry buffer to prevent expiry is too far error

---

validity-prover/.env.example
validity-prover/src/api/health.rs
validity-prover/src/api/mod.rs
validity-prover/src/api/state.rs
validity-prover/src/app/error.rs
validity-prover/src/app/observer_common.rs
validity-prover/src/app/rate_manager.rs
validity-prover/src/app/validity_prover.rs
validity-prover/src/lib.rs
validity-prover/src/main.rs

We use a rate manager to monitor job thread heartbeats. If a heartbeat exceeds the `THREAD_HEARTBEAT_TIMEOUT` threshold, the health check will fail.
This allows us to monitor silent failures or hanging jobs through the health check mechanism.
`THREAD_HEARTBEAT_TIMEOUT=600`
This pull request introduces a new health check endpoint and refactors the `State` and `ValidityProver` structures to enhance maintainability and functionality. Key changes include the addition of a `/health-check` endpoint, the introduction of a `HealthCheckConfig` for heartbeat monitoring, and the integration of `RateManager` into various components to improve rate management.
* Added a `/health-check` endpoint in `validity-prover/src/api/health.rs` to monitor the system's health by checking heartbeat timestamps and …

feat: monitoring job threads heartbeats using rate manager

---

server-common/src/redis/task_manager.rs

This pull request makes a minor improvement to the `TaskManager` implementation in `server-common/src/redis/task_manager.rs` by cleaning up the `cleanup_inactive_tasks` method. The changes remove an unnecessary infinite loop and ensure the function returns `Ok(())` at the end.
Key changes:
* Removed an infinite `loop` that was no longer needed in the `cleanup_inactive_tasks` method.
* Added an explicit `Ok(())` return statement at the end of the `cleanup_inactive_tasks` method to ensure proper function termination.

fix: remove loop inside cleanup_inactive_tasks

---

block-builder/src/app/block_builder.rs
block-builder/src/app/storage/nonce_manager/redis_nonce_manager.rs
block-builder/src/app/storage/redis_storage.rs
cli/src/cli/send.rs

Fixed a bug where tasks would be added infinitely when the nonce didn't match in dequeue_block_post_task.

fix(block-builder): redis nonce bug

---

Cargo.lock
withdrawal-server/Cargo.toml
withdrawal-server/src/api/routes.rs
withdrawal-server/src/api/state.rs
withdrawal-server/src/app/withdrawal_server.rs

Added state test, refactored helpers and laid the foundation for actix-web tests

test: add actix-web and state tests
