- .lefthook.yml
- README.md
Introduced lefthook for git hooks management.
Currently, it automates rust code formatting (`rustfmt` same as `cargo fmt`) as a pre-commit hook.
* Added lefthook configuration file (.lefthook.yml)
* Configured rustfmt to run on pre-commit
* Added lefthook setup instructions to README
* Automates code formatting standardization, reducing review workload
* Eliminates the need for format-fixing commits by formatting before commit
* Enables team-wide sharing of git hooks, making development environment standardization easier
* Lefthook is lightweight and easy to set up
> Add cargo fmt pre-commit hook

- .github/dependabot.yml
Introduced Dependabot for automated dependency updates.
It checks for updates in both Rust packages and GitHub Actions dependencies on a weekly basis.
* Added Dependabot configuration file (.github/dependabot.yml)
* Added Cargo package update settings (weekly, direct dependencies only)
* Added GitHub Actions update settings (weekly)
* Configured automatic labeling for PRs
* Defined commit message format (Cargo: chore, Actions: ci)
* Improves security through automated dependency updates
* Weekly updates keep update scope manageable
* PR limit (max 5) helps manage review workload
* Automatic labels and commit messages make changes easily trackable
* Limiting to direct dependencies prevents unnecessary updates
> Add Dependabot configuration for dependency updates

- .github/workflows/ci.yaml
Unified Rust toolchain settings and introduced caching in CI workflow.
* Fixed all jobs to use `nightly-2024-09-17` toolchain, because settings by `rust-toolchain.toml`
* Previously mixed between stable and nightly (unversioned)
* Added Swatinem/rust-cache to all jobs
* Improves CI reproducibility through fixed toolchain version
* Significantly reduces CI execution time (from ~8min to ~4min) with caching
> Fix Rust toolchain versioning and add caching in CI

- README.md
- compose.yml
- docker/tempo.local.yaml
Updated local environment setup to use Docker Compose.
* Added compose.yml, use with postgres, tempo, grafana
* Simplified environment setup with single docker compose up -d command
* Easy environment sharing across all developers
> Add docker compose for local env

- client-sdk/src/external_api/contract/rollup_contract.rs
- validity-prover/src/app/observer.rs
When deposit events obtained from RPC are missing, deposit_sync_eth_block_num might advance while some deposits are overlooked. To address this, I implemented periodic checks of the deposit index from the rollup contract. If any deposits are found to be missed, the system will raise an error and roll back deposit_sync_eth_block_num to ensure no deposits are skipped.
> Fix deposit observer bug

- .sqlx/query-17e83c47256da932aa063a002e8ab699df94bd1b168cc090dce01cbe1733fe1b.json
- .sqlx/query-5602b16bb2e9bd52ff4b0df870d25694e0fd5c06408fa0521d8a0fe46dac961b.json
- client-sdk/src/external_api/store_vault_server.rs
- interfaces/src/api/error.rs
- interfaces/src/api/store_vault_server/types.rs
- interfaces/src/api/withdrawal_server/types.rs
- interfaces/src/utils/circuit_verifiers.rs
- store-vault-server/src/app/store_vault_server.rs
- wasm/js-test/src/main.ts
- wasm/js-test/src/store_vault.ts
- wasm/src/js_types/auth.rs
- wasm/src/js_types/encrypted_data.rs
- wasm/src/js_types/mod.rs
- wasm/src/lib.rs
- wasm/src/native.rs
Refactored auth getter methods in store-vault-server/withdrawal-server to be reusable
This change enables the frontend to check for new data without using the private key each time.
Changes:
- store-vault-server
* Modified get_data_sequence to support both ascending and descending order queries
* Enhanced security by including method name in auth signature verification
- withdrawal-server
* Added method name to auth signature verification
- wasm
* Added new methods: generate_auth_for_store_vault and fetch_encrypted_data
> Make auth of getter methods in store-vault-server/withdrawal-server to be reusable

- block-builder/.env.example
- client-sdk/src/external_api/contract/error.rs
- client-sdk/src/external_api/contract/handlers.rs
You can now configure the initial `max_priority_fee_per_gas` value per chain by setting the `INITIAL_MAX_PRIORITY_FEE_PER_GAS` environment variable using the format `chain_id:gas,...`
Example:
```bash
INITIAL_MAX_PRIORITY_FEE_PER_GAS="1:1000000000,137:30000000000"
> initial max priority fee

- interfaces/src/utils/circuit_verifiers.rs
* Added `#[ignore]` attribute to long-running tests
* test_save_single_claim_verifier
* test_claim
> skip slow tests

- interfaces/src/api/validity_prover/types.rs
- validity-prover/src/api/witness_generator.rs
Added `validity-prover/get-validity-pis` to enable retrieving isValidBlock and related information through explore
> Added `get-validity-pis` endpoint

- .github/workflows/release.yml
Added automated release workflow triggered by tag creation.
tagging rule is `vX.Y.Z`
* Added new GitHub Actions release workflow
* Build for x86_64 and aarch64 Linux
* Automated release artifact creation
* Build artifact packaging
* Including intmax2-cli and block-builder
> Add automated release(create binary image) workflow

- .github/workflows/docker-image-push.yml
Added workflow to automatically push Docker images to GitHub Container Registry on tag creation.
tagging rule is `vX.Y.Z`
* Added Docker image build and push workflow
* Build for x86_64 and ARM architecture
> Add Docker image release workflow

- .sqlx/query-cd02309fc23102581d80bf91fcaecab0ff5a132b0b44de88f6132dab96f433ed.json
- Cargo.lock
- Cargo.toml
- block-builder/src/app/block_post.rs
- client-sdk/src/client/strategy/deposit.rs
- client-sdk/src/client/strategy/transfer.rs
- client-sdk/src/client/strategy/tx.rs
- client-sdk/src/client/strategy/withdrawal.rs
- client-sdk/src/external_api/private_zkp_server.rs
- client-sdk/src/external_api/validity_prover.rs
- interfaces/src/api/validity_prover/interface.rs
- interfaces/src/api/validity_prover/types.rs
- validity-prover/src/api/witness_generator.rs
- validity-prover/src/app/witness_generator.rs
Introduced new batch APIs to the Validity Prover and replaced multiple single queries with batched operations to improve performance and reduce the number of API calls.
- `get_deposit_info_batch`
- `get_account_info_batch`
- `get_block_number_by_tx_tree_root_batch`
- Client's fetch history functionality
- Client's strategy determination process
- Block builder's post block queries
> Added batch APIs to Validity Prover

- Cargo.lock
- Cargo.toml
- client-sdk/src/external_api/store_vault_server.rs
- interfaces/src/api/error.rs
- interfaces/src/api/store_vault_server/interface.rs
- store-vault-server/.env.example
- store-vault-server/src/api/routes.rs
- store-vault-server/src/app/store_vault_server.rs
- store-vault-server/src/lib.rs
Introduces batch size limitations and automatic chunking mechanism to improve system stability.
**Key changes:**
- Set `MAX_BATCH_SIZE` constant to `256` items
- Added automatic request chunking in client SDK
- Implemented batch size validation across endpoints
- Removed redundant `max_pagination_limit` config
- Bumped version from` 0.1.12` to `0.1.13`
> Introduces batch size limitations to store-vault-server

- validity-prover/migrations/20250307095617_del_index_for_leaves.down.sql
- validity-prover/migrations/20250307095617_del_index_for_leaves.up.sql
This PR adds migration scripts to remove two indexes ( `idx_leaves_lookup` and `idx_leaves_timestamp` ) from the leaves table. These indexes are not being effectively utilized in our current query patterns and are being removed to improve database performance.
> remove: db index for validity-prover's leaves table

- validity-prover/migrations/20250312133639_del_index_for_hash_nodes.down.sql
- validity-prover/migrations/20250312133639_del_index_for_hash_nodes.up.sql
- validity-prover/src/trees/merkle_tree/mod.rs
This PR includes two main changes:
* Addition of migration scripts to remove an unused index ( `idx_hash_nodes_timestamp` ) from the `hash_nodes` table
* Addition of two performance tests for the Merkle tree implementation:
* A test to measure the performance of SELECT query patterns (for #203 )
* A test to measure the performance of tree reset operations (for this changes)
> hash_nodes Index Optimization and Performance Tests Addition

- .sqlx/query-5d8aa4b3337528381f508ce98fee9fae04337bc51c427972bb91aef4efa526e7.json
- validity-prover/src/trees/merkle_tree/mod.rs
- validity-prover/src/trees/merkle_tree/sql_node_hash.rs
This PR enhances performance optimizations for query hash_nodes and adds comprehensive test coverage:
* Added `bulk_get_sibling_hashes` method to retrieve multiple node hashes with a single SQL query
* Improved the prove method to use bulk retrieval instead of individual hash lookups, reducing database access
* Added `test_speed_incremental_merkle_tree_prove` test to measure `prove` performance
* Added unit tests
performance has significantly improved. The implementation of bulk hash retrieval reduced the time for 5000 proof generations from 63.1 seconds to 7.9 seconds (an 87% reduction).
benchmark script: `validity-prover/src/trees/merkle_tree/mod.rs:test_speed_incremental_merkle_tree_prove`
```
running 1 test
test trees::merkle_tree::tests::test_speed_incremental_merkle_tree_prove has …
```
> Perf hash nodes

- .config/nextest.toml
- README.md
- validity-prover/src/trees/merkle_tree/sql_indexed_merkle_tree.rs
* modified Nextest configuration to change test thread count from a fixed value to "number of available CPUs"
* avoid risk of interference between test cases (using different tag values)
* Improved test execution speed (maximizing multi-core CPU utilization)
https://github.com/InternetMaximalism/intmax2/actions/runs/13892225012/job/38866040655#step:13:66
```
Summary [ 406.146s] 28 tests run: 28 passed (2 slow), 11 skipped
```
https://github.com/InternetMaximalism/intmax2/actions/runs/13961515454/job/39083596369#step:13:60
```
Summary [ 158.047s] 28 tests run: 28 passed (2 slow), 11 skipped
```
> avoid conflict test and set num-cpus for nextest test-threads

- validity-prover/src/trees/merkle_tree/mod.rs
- validity-prover/src/trees/merkle_tree/sql_indexed_merkle_tree.rs
This PR significantly improves the Indexed Merkle Tree implementation and expands test coverage:
* Optimized the update_leaf method to use bulk_get_sibling_hashes for Merkle path updates
* Added `test_speed_prove_and_update` performance benchmark test
* Improved performance for Merkle tree update operations (fetching multiple node hashes with a single query)
* Significantly reduced database access count, increasing overall throughput
run `trees::merkle_tree::tests::test_speed_prove_and_update` test, and check execution time.
Benchmark measurements show approximately 2x speed improvement 👍 
```
running 1 test
test trees::merkle_tree::tests::test_speed_prove_and_update has been running for over 60 seconds
SqlIndexedMerkleTree.prove_and_insert: 1000 times, 32 height, 68.938687666 seconds …
```
> improve perf for SqlIndexedMerkleTree.update_leaf

- client-sdk/src/external_api/s3_store_vault.rs
- interfaces/src/api/s3_store_vault/types.rs
- wasm/js-test/src/store_vault.ts
- wasm/src/native.rs
- Implemented parallel execution for upload/download operations in the S3 store vault client.
- Added `use_s3` as the second parameter to the `generate_auth_for_store_vault` function in the Wasm implementation.
> Fix store vault auth in WASM & parallel download/upload

- block-builder/.env.example
- block-builder/src/app/block_builder.rs
- block-builder/src/app/storage/config.rs
- block-builder/src/app/storage/redis_storage.rs
- block-builder/src/lib.rs
When you specify a `CLUSTER_ID`, that value is used as a prefix in Redis. This is useful when running multiple block builder clusters on the same Redis instance.
> Add block builder cluster id

- client-sdk/src/client/client.rs
- client-sdk/src/client/history.rs
- client-sdk/src/client/strategy/deposit.rs
- client-sdk/src/client/strategy/error.rs
- client-sdk/src/client/strategy/mining.rs
- client-sdk/src/client/strategy/mod.rs
- client-sdk/src/client/strategy/strategy.rs
- client-sdk/src/client/strategy/transfer.rs
- client-sdk/src/client/strategy/tx.rs
- client-sdk/src/client/strategy/utils.rs
- client-sdk/src/client/strategy/withdrawal.rs
- client-sdk/src/client/sync/balance_logic.rs
- client-sdk/src/client/sync/error.rs
- client-sdk/src/client/sync/sync_balance.rs
- client-sdk/src/client/sync/sync_claims.rs
- client-sdk/src/client/sync/sync_withdrawals.rs
- client-sdk/src/client/sync/utils.rs
There was an issue where data that shouldn't time out was incorrectly timing out when the validity prover wasn't synchronized. This problem was resolved by changing the current time used for timeout determination to a time when the validity prover's synchronization is guaranteed to be complete.
Additionally, a bug was fixed where `processed_digest` and `pending_digest` were confused with each other, which had caused duplicate fetching.
> Fixed Timeout and Duplicate Fetch Problems

- cli/src/cli/client.rs
- cli/src/env_var.rs
- client-sdk/src/external_api/private_zkp_server.rs
- wasm/js-test/src/setup.ts
- wasm/src/client.rs
In this PR, you will be able to specify max retries and retry interval via following env.
`PRIVATE_ZKP_SERVER_MAX_RETRIES`
`PRIVATE_ZKP_SERVER_RETRY_INTERVAL`
> Specify private zkp server's retry setting via env.

- interfaces/src/api/s3_store_vault/types.rs
- interfaces/src/api/store_vault_server/types.rs
This PR fixes a bug where the public key was not included in the authentication signatures for store-vault/s3-store-vault, which could lead to authentication failures.
> Fixed missing pubkey in store-vault/s3-store-vault authentication signatures

- client-sdk/src/client/fee_payment.rs
Instead of outputting an error when fee transfers are not settled, we modified it to ignore them.
> ignore not settled fee

- cli/src/cli/deposit.rs
- cli/src/cli/error.rs
- cli/src/env_var.rs
- client-sdk/src/external_api/mod.rs
- client-sdk/src/external_api/predicate.rs
When the following two environment variables are specified in the CLI, use them to obtain AML permission and include it in the deposit.
```
PREDICATE_BASE_URL
AML_PERMITTER_CONTRACT_ADDRESS
```
> CLI: AML Predicate

- server-common/src/db.rs
The validity prover is generating too many logs, so we should change the database logging level from info to debug to reduce the log volume.
> change log-level of db from info to debug

- Cargo.lock
- interfaces/Cargo.toml
- interfaces/src/data/encryption/bls/v1/algorithm.rs
- interfaces/src/data/encryption/bls/v1/chaum_pedersen.rs
- interfaces/src/data/encryption/bls/v1/message.rs
- interfaces/src/data/encryption/bls/v1/mod.rs
- interfaces/src/data/encryption/bls/v1/multisig.rs
- interfaces/src/data/encryption/bls/v1/utils.rs
- wasm/src/js_types/multisig.rs
When decrypting data encrypted using a multisig address, verify that the partial decryption key received from another party can only be generated by that specific individual.
The submitter of each share attaches a Chaum–Pedersen proof, and the aggregator of the shares verifies it.
> Add ECDH share validation

- Cargo.lock
- block-builder/Cargo.toml
- block-builder/src/api/state.rs
- block-builder/src/app/block_builder.rs
- block-builder/src/app/fee.rs
- block-builder/src/app/storage/memory_storage.rs
- block-builder/src/app/storage/redis_storage.rs
- block-builder/src/app/types.rs
Added tests and added balance_provider in BlockBuilder for mocking (some tests require running docker service).
Tried to refactor _from_tx_requests_ from ProposalMemo in types.rs. In short, _Sorted_and_padded_txs_ must always be the size of NUM_SENDERS_IN_BLOCK. Otherwise, panic occurs in intmax2-zkp.
> Added tests for block_builder

- .sqlx/query-2b28fb656aa5853a3a7683a24f894b35a06e1c90bf9948f28ab9b320d0f8f20d.json
- .sqlx/query-c3c9b812114c4d838f006b72147a6eee3380551424c8d7b95bcf5160f06283ad.json
- .sqlx/query-e8f56279f670e4057330cbe1d6f37d5fb4666606223d300e71a70e66e20947a3.json
- README.md
- cli/src/cli/get.rs
- interfaces/src/api/withdrawal_server/interface.rs
- wasm/src/js_types/common.rs
- withdrawal-server/migrations/20250501090900_add_l1_tx_hash.down.sql
- withdrawal-server/migrations/20250501090900_add_l1_tx_hash.up.sql
- withdrawal-server/src/app/withdrawal_server.rs
Added l1 tx hash to withdrawal info/claim info to display the corresponding l1 tx hash for withdrawals/claims on the frontend.
- Added l1_tx_hash field to withdrawal info and claim info.
- Migration of the withdrawal server will be required.
> L1 tx hash for withdrawal and claim

- cli/src/args.rs
- cli/src/cli/get.rs
- cli/src/main.rs
- client-sdk/src/client/strategy/strategy.rs
- client-sdk/src/client/sync/sync_claims.rs
- client-sdk/src/client/sync/sync_withdrawals.rs
1. Added commands to the CLI to check user-data and payment memo. This helps with debugging the status of payment memos and synchronization states.
2. In `determine_withdrawal` and `determine_claim`, we now check the request status of the withdrawal server, and exclude duplicates from `sync_withdrawals`/`sync_claims`. This prevents duplicate requests to the withdrawal server even if `user_data` updates fail during `sync_withdrawals`/`sync_claims`.
> Fix `sync_withdrawals` & `sync_claims` duplication bug

- Cargo.lock
- Cargo.toml
- validity-prover/src/app/observer.rs
- validity-prover/src/app/validity_prover.rs
- Fixed an issue where the observer would panic when `local_last_eth_block_number` was `None` and `is_synced` was `true`
- Fixed a potential issue in reset merkle tree where the reset could be insufficient if the `block_number` argument was too large
> fix: observer panic bug & better reseting

- .sqlx/query-925c271aa1f900705e6f7e1a318a13dda04d3b27dece5889fb4a61463953282d.json
- interfaces/src/api/withdrawal_server/interface.rs
- wasm/src/js_types/common.rs
- withdrawal-server/migrations/20250515135804_add_submit_claim_tx_hash.down.sql
- withdrawal-server/migrations/20250515135804_add_submit_claim_tx_hash.up.sql
- withdrawal-server/src/app/withdrawal_server.rs
This pull request introduces a new column, `submit_claim_proof_tx_hash`, to the `claims` table and propagates this change throughout the codebase to support its usage. The updates include database migrations, query modifications, and adjustments to related data structures and interfaces.
* Added a new column `submit_claim_proof_tx_hash` of type `CHAR(66)` to the `claims` table via an `up` migration and provided a corresponding `down` migration to drop the column. (`withdrawal-server/migrations/20250515135804_add_submit_claim_tx_hash.up.sql`, `withdrawal-server/migrations/20250515135804_add_submit_claim_tx_hash.down.sql`) [[1]](diffhunk://#diff-e8eb0329c931b8daa712fc1ea66e3ab55722c88be5afefc0c26b548f1a0b8ebeR1-R2) [[2]](diffhunk://#diff-3a6cc754441e56c99aa1d06d38092a6bf5c5c5267fa7ccd9d45ad9 …
> feat!(withdrawal-server/wasm): add `submit_claim_proof_tx_hash` to ClaimInfo

- Cargo.lock
- Cargo.toml
- validity-prover/src/api/state.rs
- validity-prover/src/app/validity_prover.rs
This pull request includes updates to the `validity-prover` codebase to improve job management logic, logging, and versioning. The most important changes involve refining conditional behavior for starting jobs, adding logging for better observability, and updating the project version.
* [`validity-prover/src/api/state.rs`](diffhunk://#diff-d564305f34e841ea7310ffea90ecc8ef735f37aabf0ffb97b1f7689978d88203R116-R121): Modified the `State` implementation to ensure `leader_election.start_job()` and `validity_prover.start_all_jobs()` are only executed when `is_sync_mode` is enabled. This ensures jobs are started conditionally based on the environment configuration.
* [`validity-prover/src/app/validity_prover.rs`](diffhunk://#diff-52a5e5ae63336b56e293ee397aabc7c566289398e45517012656fa9d9db5f451L47 …
> fix(validity-prover): start sync only if `is_sync_mode=true`

- cli/src/cli/get.rs
- validity-prover/src/app/observer_common.rs
- validity-prover/src/app/validity_prover.rs
This pull request includes updates to improve logging clarity, enhance functionality in the `ValidityProver` implementation, and adjust rate management logic. Below is a summary of the most significant changes:
* Updated error messages in `sync_events_job` to swap the terms "panic" and "error" for better accuracy in describing failure scenarios. (`validity-prover/src/app/observer_common.rs`)
* Added calls to `self.rate_manager.add` with appropriate keys (`SYNC_VALIDITY_WITNESS_KEY`, `GENERATE_VALIDITY_PROOF_KEY`, `ADD_TASKS_KEY`) in the `ValidityProver` implementation to track rate-limited operations. (`validity-prover/src/app/validity_prover.rs`) [[1]](diffhunk://#diff-52a5e5ae63336b56e293ee397aabc7c566289398e45517012656fa9d9db5f451R196) …
> fix: change calling place of `rate_manager.add()` & misc modifications

- validity-prover/src/api/health.rs
- validity-prover/src/app/observer_common.rs
- validity-prover/src/app/observer_graph.rs
- validity-prover/src/app/observer_rpc.rs
- validity-prover/src/app/rate_manager.rs
- validity-prover/src/app/validity_prover.rs
I've modified the heartbeat sending mechanism to occur at the beginning of each loop's internal process.
Previously, heartbeats were only sent within lower-level loops, but this created a scenario where heartbeats could be missed when higher-level loops exited before executing lower-level loops.
By implementing heartbeat transmission in higher-level loops as well, this issue has been resolved.
> fix: emit more heartbeat

- client-sdk/src/client/client.rs
- client-sdk/src/client/error.rs
- client-sdk/src/client/fee_payment.rs
- client-sdk/src/client/receipt.rs
- client-sdk/src/client/receive_validation.rs
- interfaces/src/data/tx_data.rs
- wasm/js-test/src/receipt.ts
- wasm/src/lib.rs
- withdrawal-server/src/app/withdrawal_server.rs
The `transfer_digest` parameter in `generate_transfer_receipt` was a value that the sender side could not obtain. In this PR, I change the parameters to `tx_digest` and `transfer_index`, which are values that the sender side can obtain.
> fix: change `generate_transfer_receipt` parameters
